#!/usr/bin/env node
// Copy ../rot/*.py and ../examples/*.rot into public/ so they can be
// fetched at runtime and written into Pyodide's virtual filesystem.
// Also emit a manifest.json so the runtime knows which files to fetch
// without hardcoding the list.
//
// Run automatically by package.json scripts (`predev`, `prebuild`) and
// also runnable directly: `node scripts/copy-rot.mjs`.

import { mkdir, readdir, copyFile, writeFile, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const WEB_ROOT = dirname(__dirname); // /web
const REPO_ROOT = dirname(WEB_ROOT); // /

const ROT_SRC = join(REPO_ROOT, "rot");
const EXAMPLES_SRC = join(REPO_ROOT, "examples");
const ROT_DEST = join(WEB_ROOT, "public", "rot_package");
const EXAMPLES_DEST = join(WEB_ROOT, "public", "rot_examples");

async function copyDir(srcDir, destDir, filter) {
  if (!existsSync(srcDir)) {
    console.error(`[copy-rot] source not found: ${srcDir}`);
    process.exit(1);
  }
  await mkdir(destDir, { recursive: true });
  const entries = await readdir(srcDir, { withFileTypes: true });
  const copied = [];
  for (const e of entries) {
    if (!e.isFile()) continue;
    if (!filter(e.name)) continue;
    await copyFile(join(srcDir, e.name), join(destDir, e.name));
    copied.push(e.name);
  }
  copied.sort();
  return copied;
}

async function main() {
  // 1. Copy rot/*.py.
  const pyFiles = await copyDir(ROT_SRC, ROT_DEST, (n) => n.endsWith(".py"));
  await writeFile(
    join(ROT_DEST, "manifest.json"),
    JSON.stringify({ files: pyFiles }, null, 2),
  );

  // 2. Copy examples/*.rot. Also bundle their contents into a single
  //    examples.json (keyed by example name without `.rot`) so the
  //    client doesn't need an extra fetch per example.
  const rotFiles = await copyDir(EXAMPLES_SRC, EXAMPLES_DEST, (n) =>
    n.endsWith(".rot"),
  );
  const examplesBundle = {};
  for (const name of rotFiles) {
    const key = name.replace(/\.rot$/, "");
    examplesBundle[key] = await readFile(join(EXAMPLES_SRC, name), "utf-8");
  }
  await writeFile(
    join(EXAMPLES_DEST, "examples.json"),
    JSON.stringify(examplesBundle, null, 2),
  );

  // 3. Surface the rot version (parsed from rot/__init__.py) so the
  //    header doesn't need to be hand-updated.
  const initPy = await readFile(join(ROT_SRC, "__init__.py"), "utf-8");
  const m = initPy.match(/__version__\s*=\s*"([^"]+)"/);
  const version = m ? m[1] : "unknown";
  await writeFile(
    join(WEB_ROOT, "src", "lib", "rot-version.ts"),
    `// AUTO-GENERATED by scripts/copy-rot.mjs. Do not edit by hand.\n` +
      `export const ROT_VERSION = ${JSON.stringify(version)};\n`,
  );

  console.log(
    `[copy-rot] copied ${pyFiles.length} .py file(s) -> public/rot_package, ` +
      `${rotFiles.length} .rot example(s) -> public/rot_examples, ` +
      `rot version ${version}.`,
  );
}

main().catch((err) => {
  console.error("[copy-rot] failed:", err);
  process.exit(1);
});
